### ISSUE TITLE
请问这个中间件配置好后如何使用？

### ISSUE THREAD

**Issue by DrPoohXi** [zhangzhishan/efb-filter-middleware#5]
需要启动什么程序吗？还是直接启动转发机器人和微信就可以了？

配置信息如下：
```yaml
version: 0.1
match_mode: fuzz
work_mode:
  - black_groups

black_groups:
  - GROUP1
  - GROUP2
  - GROUP3
```

以黑名单的方式过滤掉`3`个群组的信息
